In [3]:
import pandas as pd
data1 = pd.read_csv('/content/1ResearchProjectData.sav',encoding='latin-1')
data1

   $FL2@(#) IBM SPSS STATISTICS 64-bit MS Windows 26.0.0.0         
0                                     Free lunch
1                                    Paid lunch     
2                                                 NaN
3                                                 NaN
4                                )/Teacher:$@Role('0'
5                                 )/Gender:$@Role('0'
6                                 )/Ethnic:$@Role('0'
7                               )/Freeredu:$@Role('0'
8                                  )/Score:$@Role('0'
9                                 )/wesson:$@Role('0'
10                                                 )